### ISSUE TITLE
ancillary files

### ISSUE THREAD

**Issue by johannct** [lephare-photoz/lephare#12]
We need to decide what to do with ext/ sed/ filt/ opa/ directories and files therein, because without a scheme, we stay in a situation where we cannot test the C++ code, unless we copy over all these locally, for the time being.

**Comment by drewoldag** [comment]
At the time of writing this, the plan is roughly as follows (@OliviaLynn please cross check me on this one if I get things wrong):

1. Zip up the existing data files and copy them to a location such as Open Science Framework (https://osf.io/) where they can be hosted and retrieved easily.
2. Write a script that will pull those files down and unzip them in the same directory as the package. For the time being (in order to introduce as few changes as possible) the file structure will look like it does in the original (gitlab) version of LePhare. 
3. Once the code is stabilized, we can start to introduce additional changes, and make the retrieval process as flexible as needed. But for now, the goal is achieve parity with the Gitlab version of the code, without including the >1Gb of data in the repo.

**Comment by OliviaLynn** [comment]
In essence done, open questions about versioning, hashing registry, etc but these are captured in later issues
