### ISSUE TITLE
import lephare creates new timed run every time

### ISSUE THREAD

**Issue by raphaelshirley** [lephare-photoz/lephare#90]
I don't think this was the intended behaviour. If there is already at least one timed run directory the LEPHAREWORK directory should be set to the <cache>/lephare/work folder which is linked to the latest run but no new run should be created and linked unless specifically requested.

**Before submitting**
Please check the following:

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [x] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by OliviaLynn** [comment]
@Olivia Note to self: wanted to reexamine - are we creating a lot of empty directories?

**Comment by drewoldag** [comment]
If there is no cached `work` directory create a new `work` directory and timestamped `run` directory. 

If there is a cached `work` directory, just use that one, and don't create a new timestamped run directory.

**Comment by drewoldag** [comment]
For logging when running lephare, can we follow the WORK symlink so that we can print where the output is actually being kept on disk using `os` in python?

**Comment by raphaelshirley** [comment]
Just to give an idea of the impact my work cache is now 4Gb from restarting and rerunning notebooks while I test stuff.

**Comment by drewoldag** [comment]
**Summarizing the list of requirements from our previous discussion**
1. If an established users that has the environmental variables (e.v.) set calls the `create_new_run` function, they will get a warning message and no new directories will be created. 
2. In order to go back to a previous run, a modern user will set their e.v.
3. Only allow `create_new_run` to be used if the LEPHAREWORK e.v. is set to the symlinked `work` directory. 

**An open question**
What approach should we take to create the directories? Doing so in the top level __init__.py file doesn't seem like the right choice in the context of `rail_lephare`. We want to be able to import lephare and set the output location in the Inform stage. And use the output from there as the input to the Estimate stage.

**Comment by raphaelshirley** [comment]
Yes that is correct. 2 should already be implemented. I think that all that is still required in PR #100 is implementing the checks in `create_new_run`

**Comment by drewoldag** [comment]
Would nice to add in metadata to the config. Would we want information in the config files so that we can tell RAIL stages what env vars to set? 

Perhaps just implementing some log files that record this information in the work directory would be better. 

- Could create a secondary config file during the inform stage, with the run directory, that would be picked up by the estimation stage and set the env vars. This could be in the model file produced by the inform stage.
